//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PhotoViewer.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PhotoViewer.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter.
        /// </summary>
        internal static string AddElement {
            get {
                return ResourceManager.GetString("AddElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap addPhoto {
            get {
                object obj = ResourceManager.GetObject("addPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ajouter depuis la base interne.
        /// </summary>
        internal static string AddPhotoFromStorage {
            get {
                return ResourceManager.GetString("AddPhotoFromStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Album.
        /// </summary>
        internal static string Album {
            get {
                return ResourceManager.GetString("Album", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Albums.
        /// </summary>
        internal static string AlbumFormTitle {
            get {
                return ResourceManager.GetString("AlbumFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom de l&apos;artiste.
        /// </summary>
        internal static string ArtistName {
            get {
                return ResourceManager.GetString("ArtistName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annuler.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Catégorie.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Commentaire.
        /// </summary>
        internal static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Créer un album.
        /// </summary>
        internal static string CreateAlbum {
            get {
                return ResourceManager.GetString("CreateAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Créer un album.
        /// </summary>
        internal static string CreateAlbumDialogFormTitle {
            get {
                return ResourceManager.GetString("CreateAlbumDialogFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer un album.
        /// </summary>
        internal static string DeleteAlbum {
            get {
                return ResourceManager.GetString("DeleteAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap deletePhoto {
            get {
                object obj = ResourceManager.GetObject("deletePhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer la photo de la base interne.
        /// </summary>
        internal static string DeletePhotoFromStorage {
            get {
                return ResourceManager.GetString("DeletePhotoFromStorage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Informations.
        /// </summary>
        internal static string Detail {
            get {
                return ResourceManager.GetString("Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap details {
            get {
                object obj = ResourceManager.GetObject("details", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Editer un album.
        /// </summary>
        internal static string EditAlbumDialogFormTitle {
            get {
                return ResourceManager.GetString("EditAlbumDialogFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer les informations de l&apos;album.
        /// </summary>
        internal static string EditAlbumInformation {
            get {
                return ResourceManager.GetString("EditAlbumInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap editIcon {
            get {
                object obj = ResourceManager.GetObject("editIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Editer une photo.
        /// </summary>
        internal static string EditPhotoDialogFormTitle {
            get {
                return ResourceManager.GetString("EditPhotoDialogFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editer les informations de la photo.
        /// </summary>
        internal static string EditPhotoInformation {
            get {
                return ResourceManager.GetString("EditPhotoInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap emptyAlbum {
            get {
                object obj = ResourceManager.GetObject("emptyAlbum", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date de prise.
        /// </summary>
        internal static string EventDate {
            get {
                return ResourceManager.GetString("EventDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Données EXIF.
        /// </summary>
        internal static string ExifInformationCategory {
            get {
                return ResourceManager.GetString("ExifInformationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap html {
            get {
                object obj = ResourceManager.GetObject("html", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importer.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap importPhoto {
            get {
                object obj = ResourceManager.GetObject("importPhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string InformationCategory {
            get {
                return ResourceManager.GetString("InformationCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Information.
        /// </summary>
        internal static string InformationDialogTitle {
            get {
                return ResourceManager.GetString("InformationDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du fabricant de l&apos;objectif.
        /// </summary>
        internal static string LensManufacturerName {
            get {
                return ResourceManager.GetString("LensManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modéle de l&apos;objectif.
        /// </summary>
        internal static string LensName {
            get {
                return ResourceManager.GetString("LensName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom du fabricant.
        /// </summary>
        internal static string ManufacturerName {
            get {
                return ResourceManager.GetString("ManufacturerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modéle du produit.
        /// </summary>
        internal static string ManufacturerProductName {
            get {
                return ResourceManager.GetString("ManufacturerProductName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap minus {
            get {
                object obj = ResourceManager.GetObject("minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nom.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap next {
            get {
                object obj = ResourceManager.GetObject("next", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ouvrir.
        /// </summary>
        internal static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Ouvrir.
        /// </summary>
        internal static string OpenDialogTitle {
            get {
                return ResourceManager.GetString("OpenDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pause {
            get {
                object obj = ResourceManager.GetObject("pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo.
        /// </summary>
        internal static string Photo {
            get {
                return ResourceManager.GetString("Photo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to La suppression de photo(s) est irréversible, êtes-vous sûr de vouloir continuer ?.
        /// </summary>
        internal static string PhotoDeleteValidationMessage {
            get {
                return ResourceManager.GetString("PhotoDeleteValidationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Détail.
        /// </summary>
        internal static string PhotoDetailFormTitle {
            get {
                return ResourceManager.GetString("PhotoDetailFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap play {
            get {
                object obj = ResourceManager.GetObject("play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir indiquer un titre pour l&apos;album..
        /// </summary>
        internal static string PleaseEnterAlbumTitle {
            get {
                return ResourceManager.GetString("PleaseEnterAlbumTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir indiquer une note valide (nombre entier)..
        /// </summary>
        internal static string PleaseEnterAValidRating {
            get {
                return ResourceManager.GetString("PleaseEnterAValidRating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir sélectionner un album..
        /// </summary>
        internal static string PleaseSelectAlbum {
            get {
                return ResourceManager.GetString("PleaseSelectAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir selectionner une ou plusieurs photos..
        /// </summary>
        internal static string PleaseSelectOneOrMorePhotos {
            get {
                return ResourceManager.GetString("PleaseSelectOneOrMorePhotos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Merci de bien vouloir selectionner une photo..
        /// </summary>
        internal static string PleaseSelectOnePhoto {
            get {
                return ResourceManager.GetString("PleaseSelectOnePhoto", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap previous {
            get {
                object obj = ResourceManager.GetObject("previous", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap removePhoto {
            get {
                object obj = ResourceManager.GetObject("removePhoto", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Supprimer de l&apos;album.
        /// </summary>
        internal static string RemovePhotoFromAlbum {
            get {
                return ResourceManager.GetString("RemovePhotoFromAlbum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sauvegarder.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diaporama.
        /// </summary>
        internal static string Slideshow {
            get {
                return ResourceManager.GetString("Slideshow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PhotoViewer - Diaporama.
        /// </summary>
        internal static string SlideshowFormTitle {
            get {
                return ResourceManager.GetString("SlideshowFormTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sous-titre.
        /// </summary>
        internal static string SubTitle {
            get {
                return ResourceManager.GetString("SubTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Titre.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher en HTML.
        /// </summary>
        internal static string ViewInHtml {
            get {
                return ResourceManager.GetString("ViewInHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Afficher les détails de la photo.
        /// </summary>
        internal static string ViewPhotoDetail {
            get {
                return ResourceManager.GetString("ViewPhotoDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enlever.
        /// </summary>
        internal static string Withdraw {
            get {
                return ResourceManager.GetString("Withdraw", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomin {
            get {
                object obj = ResourceManager.GetObject("zoomin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap zoomout {
            get {
                object obj = ResourceManager.GetObject("zoomout", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
